export interface NhanVien {
    ngay: string,
    ngayCong: number,
    gioVao: string,
    gioRa: string,
    nghiPhep: number,
    nghiLe: number,
    nghiViecRieng: number,
    dt_NgayThuong: number,
    dt_NgayNghi: number,
    lt_NgayThuong_Tgbd: string,
    lt_NgayThuong_Tgkt: string,
    lt_NgayThuong_Sogio: number,
    lt_NgayThuong_Noidungcv: string,
    lt_NgayNghi_Tgbd: string,
    lt_NgayNghi_Tgkt: string,
    lt_NgayNghi_Sogio: number,
    lt_NgayNghi_Noidungcv: string,
    lt_NgayLe_Tgbd: string,
    lt_NgayLe_Tgkt: string,
    lt_NgayLe_Sogio: number,
    lt_NgayLe_Noidungcv: string,
    dkct_Tgbd: string,
    dkct_Tgkt: string,
    dkct_noidung: string,
    dkct_diadiem: string
}

export const NhanViens: NhanVien[] = [
    {
        ngay: "2022-12-01",
        ngayCong: 1,
        gioVao: '08:00',
        gioRa: '17:20',
        nghiPhep: 0,
        nghiLe: 1,
        nghiViecRieng: 1,
        dt_NgayThuong: 0,
        dt_NgayNghi: 0,
        lt_NgayThuong_Tgbd: '17:30',
        lt_NgayThuong_Tgkt: '21:30',
        lt_NgayThuong_Sogio: 4,
        lt_NgayThuong_Noidungcv: 'Dạy bồi dưỡng',
        lt_NgayNghi_Tgbd: '08:00',
        lt_NgayNghi_Tgkt: '17:00',
        lt_NgayNghi_Sogio: 8,
        lt_NgayNghi_Noidungcv: 'Đi du lịch',
        lt_NgayLe_Tgbd: '08:00',
        lt_NgayLe_Tgkt: '17:00',
        lt_NgayLe_Sogio: 8,
        lt_NgayLe_Noidungcv: 'Lễ sinh nhật',
        dkct_Tgbd: '08:00',
        dkct_Tgkt: '17:00',
        dkct_noidung: 'Đi tiếp khách',
        dkct_diadiem: 'Rừng Sác'
    },
    {
        ngay: "2022-12-02",
        ngayCong: 1,
        gioVao: '08:00',
        gioRa: '17:20',
        nghiPhep: 0,
        nghiLe: 1,
        nghiViecRieng: 1,
        dt_NgayThuong: 0,
        dt_NgayNghi: 0,
        lt_NgayThuong_Tgbd: '17:30',
        lt_NgayThuong_Tgkt: '21:30',
        lt_NgayThuong_Sogio: 4,
        lt_NgayThuong_Noidungcv: 'Dạy bồi dưỡng',
        lt_NgayNghi_Tgbd: '08:00',
        lt_NgayNghi_Tgkt: '17:00',
        lt_NgayNghi_Sogio: 8,
        lt_NgayNghi_Noidungcv: 'Đi du lịch',
        lt_NgayLe_Tgbd: '08:00',
        lt_NgayLe_Tgkt: '17:00',
        lt_NgayLe_Sogio: 8,
        lt_NgayLe_Noidungcv: 'Lễ sinh nhật',
        dkct_Tgbd: '08:00',
        dkct_Tgkt: '17:00',
        dkct_noidung: 'Đi tiếp khách',
        dkct_diadiem: 'Rừng Sác'
    },
    {
        ngay: "2022-12-03",
        ngayCong: 1,
        gioVao: '08:00',
        gioRa: '17:20',
        nghiPhep: 0,
        nghiLe: 1,
        nghiViecRieng: 1,
        dt_NgayThuong: 0,
        dt_NgayNghi: 0,
        lt_NgayThuong_Tgbd: '17:30',
        lt_NgayThuong_Tgkt: '21:30',
        lt_NgayThuong_Sogio: 4,
        lt_NgayThuong_Noidungcv: 'Dạy bồi dưỡng',
        lt_NgayNghi_Tgbd: '08:00',
        lt_NgayNghi_Tgkt: '17:00',
        lt_NgayNghi_Sogio: 8,
        lt_NgayNghi_Noidungcv: 'Đi du lịch',
        lt_NgayLe_Tgbd: '08:00',
        lt_NgayLe_Tgkt: '17:00',
        lt_NgayLe_Sogio: 8,
        lt_NgayLe_Noidungcv: 'Lễ sinh nhật',
        dkct_Tgbd: '08:00',
        dkct_Tgkt: '17:00',
        dkct_noidung: 'Đi tiếp khách',
        dkct_diadiem: 'Rừng Sác'
    },
    {
        ngay: "2022-12-04",
        ngayCong: 1,
        gioVao: '08:00',
        gioRa: '17:20',
        nghiPhep: 0,
        nghiLe: 1,
        nghiViecRieng: 1,
        dt_NgayThuong: 0,
        dt_NgayNghi: 0,
        lt_NgayThuong_Tgbd: '17:30',
        lt_NgayThuong_Tgkt: '21:30',
        lt_NgayThuong_Sogio: 4,
        lt_NgayThuong_Noidungcv: 'Dạy bồi dưỡng',
        lt_NgayNghi_Tgbd: '08:00',
        lt_NgayNghi_Tgkt: '17:00',
        lt_NgayNghi_Sogio: 8,
        lt_NgayNghi_Noidungcv: 'Đi du lịch',
        lt_NgayLe_Tgbd: '08:00',
        lt_NgayLe_Tgkt: '17:00',
        lt_NgayLe_Sogio: 8,
        lt_NgayLe_Noidungcv: 'Lễ sinh nhật',
        dkct_Tgbd: '08:00',
        dkct_Tgkt: '17:00',
        dkct_noidung: 'Đi tiếp khách',
        dkct_diadiem: 'Rừng Sác'
    },
    {
        ngay: "2022-12-05",
        ngayCong: 1,
        gioVao: '08:00',
        gioRa: '17:20',
        nghiPhep: 0,
        nghiLe: 1,
        nghiViecRieng: 1,
        dt_NgayThuong: 0,
        dt_NgayNghi: 0,
        lt_NgayThuong_Tgbd: '17:30',
        lt_NgayThuong_Tgkt: '21:30',
        lt_NgayThuong_Sogio: 4,
        lt_NgayThuong_Noidungcv: 'Dạy bồi dưỡng',
        lt_NgayNghi_Tgbd: '08:00',
        lt_NgayNghi_Tgkt: '17:00',
        lt_NgayNghi_Sogio: 8,
        lt_NgayNghi_Noidungcv: 'Đi du lịch',
        lt_NgayLe_Tgbd: '08:00',
        lt_NgayLe_Tgkt: '17:00',
        lt_NgayLe_Sogio: 8,
        lt_NgayLe_Noidungcv: 'Lễ sinh nhật',
        dkct_Tgbd: '08:00',
        dkct_Tgkt: '17:00',
        dkct_noidung: 'Đi tiếp khách',
        dkct_diadiem: 'Rừng Sác'
    }
]